-- 1 CRIAR A BASE DE DADOS
USE ABD_03361_A_SARAH_NARAYAMY;
 
-- 2 CRIAR A TABELA DE CLIENTES_BANCO_ITAU
-- CAMPOS:
-- ID_CLIENTE (INT AUTO_INCREMENT, PRIMARY KEY)
-- NOME_CLIENTE (VARCHAR 100)
-- CPF (VARCHAR 11)

CREATE TABLE CLIENTES_BANCO_ITAU (
 	ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(100),
    CPF VARCHAR(11)
 );
 
-- 3 CRIAR A TABELA DE CONTAS
-- CAMPOS:
-- ID_CONTA (INT AUTO_INCREMENT, PRIMARY KEY)
-- ID_CLIENTE (INT, FK)
-- SALDO (DECIMAL 10,2)
-- TIPO_CONTA (VARCHAR 20)

CREATE TABLE CONTAS (
 	ID_CONTA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT,
    SALDO DECIMAL(10,2),
    TIPO_CONTA VARCHAR(20),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES_BANCO_ITAU(ID_CLIENTE)
 );
 
-- 4 POPULAR A TABELA CLIENTES COM 5 CLIENTES SEM DEFINIR AS COLUNAS

INSERT INTO CLIENTES_BANCO_ITAU
VALUES 
(NULL, 'Ana Souza', '12345678901'),
(NULL, 'Bruno Lima', '23456789012'),
(NULL, 'Carla Mendes', '34567890123'),
(NULL, 'Diego Santos', '45678901234'),
(NULL, 'Eduarda Pereira', '56789012345');

SELECT * FROM CLIENTES_BANCO_ITAU;

-- 5 POPULAR A TABELA CONTAS COM 5 CONTAS

INSERT INTO CONTAS
VALUES
(NULL, 1, 1500.00, 'Corrente'),
(NULL, 2, 3200.50, 'Poupança'),
(NULL, 3, 850.75, 'Corrente'),
(NULL, 4, 12000.00, 'Salário'),
(NULL, 5, 500.00, 'Poupança');

SELECT * FROM CONTAS;
 
-- 6 EXERCÍCIO DE TRANSACÇÃO COM RELAÇÃO ENTRE CLIENTES E CONTAS
-- SITUAÇÃO: QUEREMOS TRANSFERIR 600 REAIS DE JOÃO SILVA PARA PEDRO LIMA
-- PASSO 1: INICIAR A TRANSACAO (BEGIN)

START TRANSACTION;

-- PASSO 2: DIMINUIR SALDO DE JOÃO SILVA

UPDATE CONTAS
SET SALDO = SALDO - 600
WHERE ID_CLIENTE = (
    SELECT ID_CLIENTE FROM CLIENTES_BANCO_ITAU
    WHERE ID_CLIENTE = 2
);

-- PASSO 3: AUMENTAR SALDO DE PEDRO LIMA

UPDATE CONTAS
SET SALDO = SALDO + 600
WHERE ID_CLIENTE = (
    SELECT ID_CLIENTE FROM CLIENTES_BANCO_ITAU
    WHERE ID_CLIENTE = 4
);

-- PASSO 4: SE SALDO DE JOÃO FICAR NEGATIVO, FAZER ROLLBACK, SENÃO COMMIT

SELECT CONCAT('R$ ', SALDO) AS SALDO
FROM CONTAS
WHERE ID_CLIENTE = (
    SELECT ID_CLIENTE FROM CLIENTES_BANCO_ITAU WHERE ID_CLIENTE = 2
);

IF @SALDO < 0 THEN
	SELECT 'ERRO' AS STATUS;
	ROLLBACK;
ELSE
	SELECT 'TRANSFERENCIA REALIZADA COM SUCESSO';
    COMMIT;
END IF;

