CREATE DATABASE BAKERY;

USE BAKERY;

-- IDENTITY: SEGUE O RACIOCINIO DO AUTO INCREMENT
-- (COMEÇA NA POSIÇÃO 1 E INCREMENTA 1 NÚMERO...
-- DÁ PARA COMEÇAR NA POSIÇÃO 2 OU OUTRA)

CREATE TABLE BAKERY_PRODUCTS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	PRODUCT_NAME VARCHAR(100) NOT NULL,
	PRICE DECIMAL(5,2) NOT NULL
);

INSERT INTO BAKERY_PRODUCTS (PRODUCT_NAME, PRICE) VALUES
('Pão Francês', 0.80),
('Croissant de Manteiga', 4.50),
('Bolo de Chocolate', 25.00),
('Torta de Limão', 18.90),
('Pão de Queijo', 1.50),
('Sonho com Creme', 5.00),
('Rosca Doce', 6.75),
('Empada de Frango', 4.20),
('Baguete Integral', 7.50),
('Cookie de Chocolate', 3.80);

SELECT
	ID,
	PRODUCT_NAME,
	CONCAT('R$ ', FORMAT(PRICE, 'N2', 'pt-BR')) AS PRICE
	FROM BAKERY_PRODUCTS;

SELECT
	ID,
	UPPER(PRODUCT_NAME) AS PRODUCT_NAME,
	CONCAT('R$ ', FORMAT(PRICE, 'N2', 'pt-BR')) AS PRICE
FROM BAKERY_PRODUCTS;

SELECT
	ID,
	LOWER(PRODUCT_NAME) AS PRODUCT_NAME,
	CONCAT('R$ ', FORMAT(PRICE, 'N2', 'pt-BR')) AS PRICE
FROM BAKERY_PRODUCTS;

SELECT
	ID,
	UPPER(PRODUCT_NAME) AS PRODUCT_NAME,
	CONCAT(LEN(PRODUCT_NAME), ' CHARACTERS') AS PRODUCT_NAME_SIZE,
	CONCAT('R$ ', FORMAT(PRICE, 'N2', 'pt-BR')) AS PRICE
FROM BAKERY_PRODUCTS;

SELECT
	ID,
	LEFT(PRODUCT_NAME, 3) AS PRODUCT_NAME,
	CONCAT('R$ ', FORMAT(PRICE, 'N2', 'pt-BR')) AS PRICE
FROM BAKERY_PRODUCTS;

SELECT
	ID,
	UPPER(PRODUCT_NAME) AS PRODUCT_NAME,
	CONCAT('R$ ', FORMAT(ROUND(PRICE,0), 'N2', 'pt-BR')) AS PRICE
FROM BAKERY_PRODUCTS;

SELECT 
	ID,
	UPPER(PRODUCT_NAME) AS PRODUCT_NAME,
	CONCAT('R$ ', FORMAT(PRICE, 'N2', 'pt-BR')) AS PRICE,
	FORMAT(GETDATE(), 'dd/MM/yyyy HH:mm:ss') AS REPORT_DATE
FROM BAKERY_PRODUCTS;

SELECT 
	ID,
	UPPER(PRODUCT_NAME) AS PRODUCT_NAME,
	CONCAT('$', FORMAT(PRICE, 'N2', 'en-US')) AS PRICE,
	FORMAT(CURRENT_TIMESTAMP, 'dd/MM/yyyy HH:mm:ss', 'pt-BR') AS REPORT_DATE
FROM BAKERY_PRODUCTS;

SELECT 
	ID,
	UPPER(PRODUCT_NAME) AS PRODUCT_NAME,
	CONCAT('R$ ', FORMAT(ROUND(PRICE,0), 'N2', 'pt-BR')) AS ROUNDED_PRICE,
	FORMAT(GETDATE(), 'dd/MM/yyyy HH:mm:ss') AS REPORT_DATE
FROM BAKERY_PRODUCTS;

