-- CONTEXTO: SISTEMA DE GESTÃO DE ESCRITÓRIO DE ADVOCACIA
 -- NOME DA BASE DE DADOS: GESTAO_ADVOCACIA_2025
 
 CREATE DATABASE ABD_03361_A_SARAH_NARAYAMY_GESTAO_ADVOCACIA_2025;
 
 USE ABD_03361_A_SARAH_NARAYAMY_GESTAO_ADVOCACIA_2025;
 
-- O OBJETIVO É RELACIONAR ADVOGADOS, CLIENTES, CASOS E AUDIENCIAS
-- E REALIZAR CONSULTAS USANDO DIFERENTES TIPOS DE JOIN
 -- 1 USAR A BASE COM SEUS NOMES
 -- 2 CRIAR A TABELA ADVOGADOS
-- CAMPOS: id, nome, oab, especialidade

CREATE TABLE LAWYERS (
 	ID INT AUTO_INCREMENT PRIMARY KEY,
    LAWYER_NAME VARCHAR(100) NOT NULL,
    OAB VARCHAR(8) NOT NULL,
    ESPECIALTY VARCHAR(50)
 );
 
-- 3 CRIAR A TABELA CLIENTES
-- CAMPOS: id, nome, cpf, cidade

CREATE TABLE CLIENTS (
 	ID INT AUTO_INCREMENT PRIMARY KEY,
    CLIENT_NAME VARCHAR(100) NOT NULL,
    CPF INT NOT NULL,
    CITY VARCHAR(50)
 );
 
-- 4 CRIAR A TABELA CASOS
-- CAMPOS: id, id_advogado, id_cliente, descricao, status, data_abertura
-- RELACIONAR id_advogado COM ADVOGADOS
-- RELACIONAR id_cliente COM CLIENTES

CREATE TABLE CASES (
 	ID INT AUTO_INCREMENT PRIMARY KEY,
    LAWYER_ID INT,
    CLIENT_ID INT,
    CASE_DESCRIPTION VARCHAR(50) NOT NULL,
    CASE_STATUS VARCHAR(20) NOT NULL,
    OPENING_DATE DATE NOT NULL,
    FOREIGN KEY (LAWYER_ID) REFERENCES LAWYERS(ID),
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(ID)
 );
 
-- 5 CRIAR A TABELA AUDIENCIAS
-- CAMPOS: id, id_caso, data_audiencia, local, resultado
-- RELACIONAR id_caso COM CASOS

CREATE TABLE HEARINGS (
 	ID INT AUTO_INCREMENT PRIMARY KEY,
    CASE_ID INT,
    HEARING_DATE DATE NOT NULL,
    COURT VARCHAR(100),
    RESULT VARCHAR(50),
    FOREIGN KEY (CASE_ID) REFERENCES CASES(ID)
 );
 
-- 6 POPULAR TODAS AS TABELAS COM PELO MENOS 5 REGISTROS
 
 INSERT INTO LAWYERS (LAWYER_NAME, OAB, ESPECIALTY) VALUES
('Mariana Alves', 'SP123456', 'Direito Civil'),
('Carlos Pereira', 'RJ654321', 'Direito Penal'),
('Fernanda Souza', 'MG789012', 'Direito Trabalhista'),
('João Costa', 'SP234567', 'Direito Empresarial'),
('Patrícia Lima', 'RS345678', 'Direito de Família'),
('Ricardo Mendes', 'PR456789', 'Direito Tributário'),
('Amanda Rocha', 'BA567890', 'Direito Ambiental'),
('Felipe Duarte', 'PE678901', 'Direito Penal'),
('Luana Martins', 'SC789013', 'Direito Civil'),
('André Silva', 'GO890124', 'Direito Constitucional');

INSERT INTO LAWYERS (LAWYER_NAME, OAB, ESPECIALTY) VALUES
('Carlos Tavares', 'SP965452', 'Direito Civil'),
('Julio Soares', 'RJ652374', 'Direito Penal'),
('Patricia dos Santos', 'MG489523', 'Direito Trabalhista'),
('Laura Cunha', 'SP214789', 'Direito Empresarial'),
('Emilia Patissery', 'RS952148', 'Direito de Família');

INSERT INTO CLIENTS (CLIENT_NAME, CPF, CITY) VALUES
('José da Silva', 123456789, 'São Paulo'),
('Maria Oliveira', 987654321, 'Rio de Janeiro'),
('Paulo Santos', 456789123, 'Belo Horizonte'),
('Ana Costa', 321654987, 'Curitiba'),
('Rafael Souza', 654987321, 'Porto Alegre'),
('Juliana Martins', 741852963, 'Salvador'),
('Lucas Pereira', 852963741, 'Recife'),
('Fernanda Lima', 963741852, 'Florianópolis'),
('Gabriel Rocha', 159753486, 'Goiânia'),
('Camila Duarte', 357159486, 'Brasília');

INSERT INTO CLIENTS (CLIENT_NAME, CPF, CITY) VALUES
('Vicencia da Silva', 569874256, 'São Paulo'),
('Maria Gabriela', 123465982, 'Rio de Janeiro'),
('Ana Clara', 952368745, 'Belo Horizonte'),
('Marcia Tavares', 563242855, 'Curitiba'),
('luiza Silveira', 214859652, 'Porto Alegre');

INSERT INTO CASES (LAWYER_ID, CLIENT_ID, CASE_DESCRIPTION, CASE_STATUS, OPENING_DATE) VALUES
(1, 1, 'Indenização por danos morais', 'Em andamento', '2024-03-12'),
(2, 2, 'Defesa criminal', 'Encerrado', '2023-11-08'),
(3, 3, 'Reclamação trabalhista', 'Em andamento', '2024-05-20'),
(4, 4, 'Abertura de empresa', 'Em andamento', '2024-09-02'),
(5, 5, 'Divórcio consensual', 'Encerrado', '2023-07-15'),
(6, 6, 'Revisão tributária', 'Em andamento', '2024-01-28'),
(7, 7, 'Licenciamento ambiental', 'Em andamento', '2024-06-30'),
(8, 8, 'Defesa criminal', 'Em andamento', '2024-04-10'),
(9, 9, 'Ação de cobrança', 'Encerrado', '2023-09-25'),
(10, 10, 'Direitos constitucionais', 'Em andamento', '2024-08-14');

INSERT INTO CASES (LAWYER_ID, CLIENT_ID, CASE_DESCRIPTION, CASE_STATUS, OPENING_DATE) VALUES
(2, NULL, 'Indenização por danos morais', 'Em andamento', '2024-03-20'),
(2, NULL, 'Defesa criminal', 'Encerrado', '2023-11-16'),
(3, NULL, 'Reclamação trabalhista', 'Em andamento', '2024-05-24'),
(4, NULL, 'Abertura de empresa', 'Em andamento', '2024-09-30'),
(5, NULL, 'Divórcio consensual', 'Encerrado', '2023-07-18');

INSERT INTO CASES (LAWYER_ID, CLIENT_ID, CASE_DESCRIPTION, CASE_STATUS, OPENING_DATE) VALUES
(NULL, NULL, 'Indenização por danos morais', 'Encerrado', '2024-03-15'),
(NULL, NULL, 'Defesa criminal', 'Encerrado', '2021-08-06'),
(NULL, NULL, 'Reclamação trabalhista', 'Encerrado', '2023-07-10'),
(NULL, NULL, 'Abertura de empresa', 'Em andamento', '2022-10-09'),
(NULL, NULL, 'Divórcio consensual', 'Encerrado', '2024-09-15');

INSERT INTO CASES (LAWYER_ID, CLIENT_ID, CASE_DESCRIPTION, CASE_STATUS, OPENING_DATE) VALUES
(NULL, 2, 'Indenização por danos morais', 'Encerrado', '2022-02-15'),
(NULL, 5, 'Defesa criminal', 'Encerrado', '2023-09-06'),
(NULL, 4, 'Reclamação trabalhista', 'Encerrado', '2024-05-10'),
(NULL, 3, 'Abertura de empresa', 'Em andamento', '2024-11-09'),
(NULL, 1, 'Divórcio consensual', 'Encerrado', '2023-06-15');

INSERT INTO HEARINGS (CASE_ID, HEARING_DATE, COURT, RESULT) VALUES
(1, '2024-06-15', 'Fórum Central SP', 'Aguardando sentença'),
(2, '2023-12-02', 'Tribunal RJ', 'Caso encerrado'),
(3, '2024-08-10', 'Fórum Trabalhista BH', 'Remarcada'),
(4, '2024-10-01', 'Fórum Empresarial SP', 'Em andamento'),
(5, '2023-09-05', 'Fórum de Família RS', 'Acordo firmado'),
(6, '2024-03-18', 'Tribunal PR', 'Audiência adiada'),
(7, '2024-09-21', 'Fórum Ambiental BA', 'Em análise'),
(8, '2024-07-04', 'Tribunal PE', 'Depoimentos colhidos'),
(9, '2023-10-13', 'Fórum Cível SC', 'Sentença proferida'),
(10, '2024-11-08', 'Tribunal GO', 'Em fase final');
 
-- CONSULTAS (EXERCÍCIOS):
 
-- 7 INNER JOIN
-- MOSTRAR O NOME DO CLIENTE, O NOME DO ADVOGADO E A DESCRIÇÃO DO CASO

-- MOSTRARÁ TODOS OS CASOS QUE TENHAM ADVOGADO E CLIENTE VINCULADOS. USEI A TABELA DE CASES PQ CONTEM DUAS FOREIGN KEYS
SELECT
	ROW_NUMBER() OVER (ORDER BY CL.CLIENT_NAME) AS QUANTIDADE,
    CL.CLIENT_NAME AS NOME,
    L.LAWYER_NAME AS ADVOGADO,
    C.CASE_DESCRIPTION AS DESCRIÇÃO
FROM CASES C
INNER JOIN CLIENTS CL ON C.CLIENT_ID = CL.ID
INNER JOIN LAWYERS L ON C.LAWYER_ID = L.ID
ORDER BY CL.CLIENT_NAME ASC;
 
-- 8 LEFT JOIN
-- MOSTRAR TODOS OS CLIENTES, MESMO OS QUE AINDA NÃO TÊM NENHUM CASO
-- A TABELA DE CLIENTES SERA A PRINCIPAL POIS EU QUERO MOSTRAR TODOS OS CLIENTES.
-- PORTANDO ELA FICA A ESQUERDA DA JUNÇÃO SENDO A PRINCIPAL PARA USAR O LEFT JOIN

SELECT
	ROW_NUMBER() OVER (ORDER BY CL.CLIENT_NAME) AS QUANTIDADE,
    CL.CLIENT_NAME AS NOME,
    L.LAWYER_NAME AS ADVOGADO,
    C.CASE_DESCRIPTION AS DESCRIÇÃO
FROM CLIENTS CL
LEFT JOIN CASES C ON CL.ID = C.CLIENT_ID
LEFT JOIN LAWYERS L ON C.LAWYER_ID = L.ID
ORDER BY CL.CLIENT_NAME ASC;

-- 9 RIGHT JOIN
-- MOSTRAR TODOS OS CASOS, MESMO OS QUE AINDA NÃO POSSUEM CLIENTE DEFINIDO
-- SE COLOCARMOS CLIENTES A ESQUERDA E CASES A DIREITA, UTILIZAMOS CLIENTS COMO PRINCIPAL
-- INICIAMOS O RIGHT JOIN PARA MOSTRAR TODOS OS CASES MESMO SEM CLIENTE
-- SEGUIDO DO LEFT JOIN MOSTRANDO TODOS OS ADVOGADOS MESMO SEM CASOS

SELECT
	ROW_NUMBER() OVER (ORDER BY CL.CLIENT_NAME) AS QUANTIDADE,
    CL.CLIENT_NAME AS NOME,
    L.LAWYER_NAME AS ADVOGADO,
    C.CASE_DESCRIPTION AS DESCRIÇÃO
FROM CLIENTS CL
RIGHT JOIN CASES C ON CL.ID = C.CLIENT_ID
LEFT JOIN LAWYERS L ON C.LAWYER_ID = L.ID
ORDER BY CL.CLIENT_NAME ASC;
 
-- 10 FULL JOIN (USAR UNION)
-- MOSTRAR TODOS OS CLIENTES E CASOS, MESMO SEM RELAÇÃO ENTRE ELES
-- SE COLOCARMOS CLIENTES A ESQUERDA E CASES A DIREITA, UTILIZANDO CLIENTS COMO PRINCIPAL
-- INICIAMOS O LEFT JOIN SEGUINDO DO LEFT JOIN PARA MOSTRAR TODOS OS CLIENTES E ADVOGADOS QUE TEM CASOS OU NÃO
-- SEGUNDO PASSO É O RIGHT JOIN MOSTRANDO TODOS OS CASOS QUE TEM CLIENTES E ADVOGADOS
-- UNION UNE AS DUAS CHAMADAS ELIMINANDO DUPLICIDADES (SIMULA O FULL OUTER JOIN)

SELECT
    CL.CLIENT_NAME AS NOME,
    L.LAWYER_NAME AS ADVOGADO,
    C.CASE_DESCRIPTION AS DESCRIÇÃO
FROM CLIENTS CL
LEFT JOIN CASES C ON CL.ID = C.CLIENT_ID
LEFT JOIN LAWYERS L ON C.LAWYER_ID = L.ID

UNION

SELECT
    CL.CLIENT_NAME AS NOME,
    L.LAWYER_NAME AS ADVOGADO,
    C.CASE_DESCRIPTION AS DESCRIÇÃO
FROM CLIENTS CL
RIGHT JOIN CASES C ON CL.ID = C.CLIENT_ID
LEFT JOIN LAWYERS L ON C.LAWYER_ID = L.ID
ORDER BY 1;
 
-- 11 CROSS JOIN
-- GERAR UMA COMBINAÇÃO ENTRE TODOS OS ADVOGADOS E TODOS OS CLIENTES
-- (POSSÍVEIS RELAÇÕES DE ATENDIMENTO)

SELECT
    L.LAWYER_NAME AS ADVOGADO,
    CL.CLIENT_NAME AS NOME
FROM LAWYERS L
CROSS JOIN CLIENTS CL
ORDER BY L.LAWYER_NAME, CL.CLIENT_NAME;
 
-- 12 MOSTRAR OS CASOS QUE ESTÃO COM STATUS 'EM ANDAMENTO' E
-- QUE FORAM ABERTOS DEPOIS DE '2025-01-01'
-- USAR INNER JOIN E WHERE
 
-- 13 MOSTRAR CADA ADVOGADO E QUANTOS CASOS ELE POSSUI
-- USAR GROUP BY E COUNT
 
-- 14 MOSTRAR OS CLIENTES ORDENADOS PELO NOME (A–Z)
-- E SUAS RESPECTIVAS CIDADES
 
-- 15 MOSTRAR O TOTAL DE AUDIENCIAS REALIZADAS EM UMA COLUNA CHAMADA TOTAL_AUDIENCIAS
-- USAR COUNT E AS
 
-- 16 MOSTRAR OS CLIENTES DA CIDADE DE 'SÃO PAULO' E OS CASOS ASSOCIADOS
-- USAR INNER JOIN E WHERE
 
-- 17 MOSTRAR OS ADVOGADOS QUE NÃO POSSUEM NENHUM CASO
-- USAR LEFT JOIN E IS NULL
 
-- 18 MOSTRAR O NÚMERO TOTAL DE CASOS EM CADA STATUS (EX: 'EM ANDAMENTO', 'ENCERRADO')
-- USAR GROUP BY, COUNT E AS
 
-- 19 MOSTRAR O ADVOGADO COM MAIS CASOS CADASTRADOS
-- DICA: USAR GROUP BY, ORDER BY E LIMIT 1