-- EU PRECISO CONTROLAR OS USUÁRIOS, EU PRECISO TER UM USUÁRIO MASTER (ROOT) QUE POSSA ADICIONAR OUTROS USUÁRIOS
-- O USUARIO MASTER DEVE CONSEGUIR CRIAR NOVOS ITENS NA TABELA DE TRANSAÇÕES (PAGAMENTOS PARA OS PROFESSORES)
-- JÁ O USUÁRIO 'NORMAL' DEVE CONSEGUIR SOMENTE VISUALIZAR
-- TODOS OS USUÁRIOS DEVEM PERTENCER A GRUPOS, NINGUEM FICA SEM GRUPO
-- UM USUÁRIO PODE PERTENCER A MAIS DE UM GRUPO OU SOMENTE 1 (EX: FINANTIAL, LEGAL, COMPLIANCE)

-- MODELANDO NO BR MODELO EM DER
-- CRIAR AS TABELAS, SUAS RELAÇÕES E POPULÁ-LAS

USE ABD_03361_A_SARAH_NARAYAMY;

-- CRIAR TABELA DE SETORES

CREATE TABLE DEPARTMENT ( 
	ID INT AUTO_INCREMENT PRIMARY KEY,  
	DEPT_NAME VARCHAR(50) NOT NULL,  
	DETAILS VARCHAR(100),  
	ID_USER INT
); 

-- CRIAR TABELA DE USUÁRIOS

CREATE TABLE USERS ( 
	ID INT AUTO_INCREMENT PRIMARY KEY,  
	FIRST_NAME VARCHAR(50) NOT NULL,  
	LAST_NAME VARCHAR(50) NOT NULL,  
	PERMISSION INT NOT NULL,  
	USER_PASSWORD VARCHAR(10) NOT NULL,  
	POSITION VARCHAR(50) NOT NULL,  
	EMAIL VARCHAR(100) NOT NULL,  
	STATE INT NOT NULL,  
	UNIQUE (USER_PASSWORD,EMAIL)
); 

-- CRIAR TABELA DE TRANSAÇÕES

CREATE TABLE TRANSACTIONS ( 
	ID INT AUTO_INCREMENT PRIMARY KEY,  
	DETAILS VARCHAR(100),  
	TRANSACTION_DATE DATE NOT NULL,  
	REFERENCE_CODE INT AUTO_INCREMENT,  
	ID_USER INT,  
	UNIQUE (REFERENCE_CODE)
);

-- DETERMINANDO AS FOREIGN KEYS DAS TABELAS DE DEPARTAMENTO E TRANSAÇÕES

ALTER TABLE DEPARTMENT ADD FOREIGN KEY(ID_USER) REFERENCES USER (ID_USER);
ALTER TABLE TRANSACTIONS ADD FOREIGN KEY(ID_USER) REFERENCES USER (ID_USER);

-- POPULANDO CADA TABELA COM 10 ENTRADAS

INSERT INTO USERS (FIRST_NAME, LAST_NAME, PERMISSION, USER_PASSWORD, POSITION, EMAIL, STATE) VALUES
('CARLOS', 'SOUZA', 1, 'ABC123', 'GERENTE', 'CARLOS.SOUZA@EMPRESA.COM', 1),
('MARTA', 'SILVA', 2, 'DEF456', 'ANALISTA', 'MARTA.SILVA@EMPRESA.COM', 1),
('JOÃO', 'PEREIRA', 2, 'GHI789', 'SUPERVISOR', 'JOAO.PEREIRA@EMPRESA.COM', 1),
('ANA', 'COSTA', 3, 'JKL321', 'COORDENADORA', 'ANA.COSTA@EMPRESA.COM', 1),
('RICARDO', 'ALMEIDA', 3, 'MNO654', 'TÉCNICO', 'RICARDO.ALMEIDA@EMPRESA.COM', 1),
('FERNANDA', 'LIMA', 2, 'PQR987', 'ASSISTENTE', 'FERNANDA.LIMA@EMPRESA.COM', 1),
('PAULO', 'ROCHA', 1, 'STU111', 'DIRETOR', 'PAULO.ROCHA@EMPRESA.COM', 1),
('JULIANA', 'MENDES', 3, 'VWX222', 'SECRETÁRIA', 'JULIANA.MENDES@EMPRESA.COM', 1),
('PEDRO', 'SANTOS', 2, 'YZA333', 'OPERADOR', 'PEDRO.SANTOS@EMPRESA.COM', 1),
('LARISSA', 'MARTINS', 2, 'BCD444', 'ANALISTA', 'LARISSA.MARTINS@EMPRESA.COM', 1);

INSERT INTO DEPARTMENT (DEPT_NAME, DETAILS, ID_USER) VALUES
('FINANCEIRO', 'RESPONSÁVEL PELO CONTROLE FINANCEIRO', 1),
('RECURSOS HUMANOS', 'GESTÃO DE PESSOAS E BENEFÍCIOS', 2),
('TECNOLOGIA', 'SUPORTE E DESENVOLVIMENTO DE SISTEMAS', 3),
('MARKETING', 'PLANEJAMENTO DE CAMPANHAS PUBLICITÁRIAS', 4),
('COMPRAS', 'AQUISIÇÃO DE MATERIAIS E SERVIÇOS', 5),
('VENDAS', 'GESTÃO DE CLIENTES E NEGOCIAÇÕES', 6),
('LOGÍSTICA', 'CONTROLE DE ESTOQUE E TRANSPORTE', 7),
('JURÍDICO', 'ASSESSORIA LEGAL E CONTRATUAL', 8),
('QUALIDADE', 'AUDITORIA E CONTROLE DE PROCESSOS', 9),
('ADMINISTRATIVO', 'SUPORTE GERAL ÀS OPERAÇÕES', 10);

INSERT INTO TRANSACTIONS (DETAILS, TRANSACTION_DATE, REFERENCE_CODE, ID_USER) VALUES
('PAGAMENTO DE FORNECEDOR', '2025-01-10', 1001, 1),
('REEMBOLSO DE DESPESAS', '2025-01-15', 1002, 2),
('COMPRA DE EQUIPAMENTOS', '2025-02-01', 1003, 3),
('VENDA DE SERVIÇOS', '2025-02-20', 1004, 4),
('RECEBIMENTO DE CLIENTE', '2025-03-05', 1005, 5),
('TRANSFERÊNCIA INTERNA', '2025-03-22', 1006, 6),
('AJUSTE CONTÁBIL', '2025-04-10', 1007, 7),
('PAGAMENTO DE SALÁRIOS', '2025-04-30', 1008, 8),
('ENTRADA DE CAPITAL', '2025-05-10', 1009, 9),
('PAGAMENTO DE IMPOSTOS', '2025-05-25', 1010, 10);

