-- EU PRECISO CONTROLAR OS USUÁRIOS, EU PRECISO TER UM USUÁRIO MASTER (ROOT) QUE POSSA ADICIONAR OUTROS USUÁRIOS
-- O USUARIO MASTER DEVE CONSEGUIR CRIAR NOVOS ITENS NA TABELA DE TRANSAÇÕES (PAGAMENTOS PARA OS PROFESSORES)
-- JÁ O USUÁRIO 'NORMAL' DEVE CONSEGUIR SOMENTE VISUALIZAR
-- TODOS OS USUÁRIOS DEVEM PERTENCER A GRUPOS, NINGUEM FICA SEM GRUPO
-- UM USUÁRIO PODE PERTENCER A MAIS DE UM GRUPO OU SOMENTE 1 (EX: FINANTIAL, LEGAL, COMPLIANCE)

-- MODELANDO NO BR MODELO EM DER
-- CRIAR AS TABELAS, SUAS RELAÇÕES E POPULÁ-LAS

USE ABD_03361_A_SARAH_NARAYAMY;

-- CRIAR TABELA DE SETORES

CREATE TABLE DEPARTMENT ( 
	ID INT AUTO_INCREMENT PRIMARY KEY,  
	DEPT_NAME VARCHAR(50) NOT NULL,  
	DETAILS VARCHAR(100),  
	ID_USER INT
); 

CREATE TABLE USERS ( 
	ID INT AUTO_INCREMENT PRIMARY KEY,  
	FIRST_NAME VARCHAR(50) NOT NULL,  
	LAST_NAME VARCHAR(50) NOT NULL,  
	PERMISSION INT NOT NULL,  
	USER_PASSWORD VARCHAR(10) NOT NULL,  
	POSITION VARCHAR(50) NOT NULL,  
	EMAIL VARCHAR(100) NOT NULL,  
	STATE INT NOT NULL,  
	UNIQUE (USER_PASSWORD,EMAIL)
); 

CREATE TABLE TRANSACTIONS ( 
	ID INT AUTO_INCREMENT PRIMARY KEY,  
	DETAILS VARCHAR(100),  
	TRANSACTION_DATE DATE NOT NULL,  
	REFERENCE_CODE INT AUTO_INCREMENT,  
	ID_USER INT,  
	UNIQUE (REFERENCE_CODE)
); 

ALTER TABLE DEPARTMENT ADD FOREIGN KEY(ID_USER) REFERENCES USER (ID_USER);
ALTER TABLE TRANSACTIONS ADD FOREIGN KEY(ID_USER) REFERENCES USER (ID_USER);