USE ABD_03361_A_SARAH_NARAYAMY;

-- CRIAR TABELA DE PRODUTO

CREATE TABLE PRODUTO (
 	ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    PRECO DECIMAL(8,2)
 );
 
-- CRIAR TABELA VENDAS
-- CRIAR UMA VARIAVEL PARA A FOREIGN KEY VINDA DE PRODUTO

CREATE TABLE VENDAS (
 	ID_VENDA INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUTO INT,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO),
    QUANTIDADE INT,
    DATA_VENDA DATE
 );
 
-- CRIAR TABELA DE FORNECEDOR
 
CREATE TABLE FORNECEDOR(
	ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    TELEFONE VARCHAR(20)
);


INSERT INTO PRODUTO (NOME, PRECO) VALUES
('PÃO FRANCÊS', 0.80),
('BOLO DE CENOURA COM COBERTURA', 25.90),
('SONHO RECHEADO', 6.50),
('CROISSANT DE CHOCOLATE', 7.20),
('TORTA DE MORANGO', 42.00);

INSERT INTO VENDAS (ID_PRODUTO, QUANTIDADE, DATA_VENDA) VALUES
(1, 50, '2025-10-01'),
(2, 3, '2025-10-02'),
(3, 10, '2025-10-03'),
(4, 7, '2025-10-04'),
(5, 2, '2025-10-05');

INSERT INTO FORNECEDOR (NOME, TELEFONE) VALUES
('PADARIA CENTRAL DE INSUMOS', '(11) 3333-1122'),
('MOINHO SÃO JORGE LTDA', '(21) 98888-4455'),
('DISTRIBUIDORA DOCE PÃO', '(31) 97777-2233'),
('CAFES PREMIUM BRASIL', '(41) 96666-7788'),
('LATICÍNIOS VALE VERDE', '(51) 95555-8899');

SELECT * FROM PRODUTO;

SELECT * FROM VENDAS;

SELECT * FROM FORNECEDOR;

SELECT * FROM VENDAS WHERE ID_PRODUTO = 3;

SELECT 
    P.NOME AS PRODUTO,
    SUM(V.QUANTIDADE) AS QUANTIDADE_TOTAL_VENDIDA
FROM VENDAS V
JOIN PRODUTO P ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE P.NOME = 'SONHO RECHEADO'
GROUP BY P.NOME;

SELECT 
    P.NOME AS PRODUTO,
    SUM(V.QUANTIDADE) AS QUANTIDADE_TOTAL_VENDIDA
FROM VENDAS V
JOIN PRODUTO P ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE P.NOME = 'TORTA DE MORANGO'
GROUP BY P.NOME;

SELECT 
    V.DATA_VENDA,
    P.NOME AS PRODUTO,
    V.QUANTIDADE,
    (P.PRECO * V.QUANTIDADE) AS TOTAL_VENDA
FROM VENDAS V
JOIN PRODUTO P ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE V.DATA_VENDA = '2025-10-03';





