USE ABD_03361_A_SARAH_NARAYAMY;

-- CRIAR UMA TABELA COM O NOME ERRADO PARA SIMULAR UM ERRO
-- OBJETIVO: PRATICAR DROP CRIANDO ALGO ERRADO DE PROPÓSITO

CREATE TABLE NOME_ERRADO_VIAGENS (
 	ID_VIAGEM INT AUTO_INCREMENT PRIMARY KEY,
    PAIS VARCHAR(100),
    CIDADE VARCHAR(100),
    CONTINENTE VARCHAR(50),
    DATA_VIAGEM DATE,
    MOEDA_LOCAL VARCHAR(10),
    NOTA INT,
    IDIOMA_PRINCIPAL VARCHAR(50),
    FOI_INTERNACIONAL BOOLEAN,
    DESEJO_VOLTAR BOOLEAN
 );
 
 -- APAGAR A TABELA COM O NOME ERRADO USANDO DROP
 -- OBJETIVO: REMOVER A TABELA INCORRETA
 
 DROP TABLE NOME_ERRADO_VIAGENS;
 
 -- CRIAR NOVAMENTE A TABELA COM O NOME CORRETO
 -- OBJETIVO: RECRIAR A TABELA COM O NOME CERTO E COLUNAS BASICAS
 
CREATE TABLE NOME_CORRETO_VIAGENS (
    ID_VIAGEM INT AUTO_INCREMENT PRIMARY KEY,
    PAIS VARCHAR(100),
    CIDADE VARCHAR(100),
    CONTINENTE VARCHAR(50),
    DATA_VIAGEM DATE,
    MOEDA_LOCAL VARCHAR(10),
    NOTA INT,
    IDIOMA_PRINCIPAL VARCHAR(50),
    FOI_INTERNACIONAL BOOLEAN,
    DESEJO_VOLTAR BOOLEAN
    );
    
        
-- ADICIONAR UMA NOVA COLUNA QUE ESQUECEMOS USANDO ALTER TABLE
-- OBJETIVO: ADICIONAR A COLUNA NOTA INT

ALTER TABLE NOME_CORRETO_VIAGENS ADD CUSTO VARCHAR(20);


-- INSERIR DOIS REGISTROS NA TABELA
-- OBJETIVO: PRATICAR INSERT COM MULTIPLAS LINHAS

 INSERT INTO NOME_CORRETO_VIAGENS (PAIS, CIDADE, CONTINENTE, DATA_VIAGEM, MOEDA_LOCAL, NOTA, IDIOMA_PRINCIPAL,
			FOI_INTERNACIONAL, DESEJO_VOLTAR, CUSTO)
VALUES 
		('BRASIL', 'RIO DE JANEIRO', 'AMÉRICA DO SUL', '2023-02-15', 'BRL', 9, 'PORTUGUÊS', FALSE, TRUE, 'ALTO'),
		('IRLANDA', 'DUBLIN', 'EUROPA', '2022-11-05', 'EUR', 7, 'INGLÊS', TRUE, TRUE, 'ALTO'),
        ('IRLANDA', 'LIMERICK', 'EUROPA', '2023-02-15', 'EUR', 8, 'INGÊS', TRUE, TRUE, 'MÉDIO'),
        ('BELGICA', 'BRUGES', 'EUROPA', '2021-02-15', 'EUR', 8, 'FRANCES', TRUE, FALSE, 'MÉDIO'),
        ('SUÉCIA', 'ESTOCOLMO', 'EUROPA', '2025-6-13', 'SEK', 10, 'SUECO', TRUE, TRUE, 'ALTO'),
        ('INGLATERRA', 'LONDRES', 'EUROPA', '2021-08-07', 'GBP', 7, 'INGLÊS', TRUE, FALSE, 'MÉDIO'),
        ('ITALIA', 'MARSALA', 'EUROPA', '2025-07-18', 'EUR', 10, 'ITALIANO', TRUE, TRUE, 'BAIXO'),
        ('ESPANHA', 'MALAGA', 'EUROPA', '2019-06-27', 'EUR', 8, 'ESPANHOL', TRUE, TRUE, 'BAIXO'),
        ('BRASIL', 'BAHIA', 'AMÉRICA DO SUL', '2006-09-17', 'BRL', 9, 'PORTUGUÊS', FALSE, TRUE, 'ALTO');
        
-- VERIFICAR SE OS DADOS FORAM INSERIDOS
-- OBJETIVO: CONFIRMAR COM SELECT SE OS DADOS ESTÃO CORRETOS

SELECT
    ID_VIAGEM,
    PAIS,
    CIDADE,
    CONTINENTE,
    DATA_VIAGEM,
    MOEDA_LOCAL,
    NOTA,
    IDIOMA_PRINCIPAL,
    IF(FOI_INTERNACIONAL, 'SIM', 'NÃO') AS FOI_INTERNACIONAL,
    IF(DESEJO_VOLTAR, 'SIM', 'NÃO') AS DESEJO_VOLTAR,
    CUSTO
FROM NOME_CORRETO_VIAGENS;

-- LIMPAR TODA A TABELA USANDO TRUNCATE
-- OBJETIVO: APAGAR TODOS OS REGISTROS RAPIDAMENTE

TRUNCATE TABLE NOME_CORRETO_VIAGENS;

-- CONFERIR QUE A TABELA ESTÁ VAZIA MAS A ESTRUTURA PERMANECE
-- OBJETIVO: TESTAR SELECT E CONFIRMAR QUE A ESTRUTURA AINDA EXISTE

SELECT COUNT(*) FROM NOME_CORRETO_VIAGENS;
SHOW TABLES;

SELECT
    ID_VIAGEM,
    PAIS,
    CIDADE,
    CONTINENTE,
    DATA_VIAGEM,
    MOEDA_LOCAL,
    NOTA,
    IDIOMA_PRINCIPAL,
    IF(FOI_INTERNACIONAL, 'SIM', 'NÃO') AS FOI_INTERNACIONAL,
    IF(DESEJO_VOLTAR, 'SIM', 'NÃO') AS DESEJO_VOLTAR,
    CUSTO
FROM NOME_CORRETO_VIAGENS;

 
 GRANT SELECT, INSERT ON NOME_CORRETO_VIAGENS TO 'professor'@'%';
 
 REVOKE SELECT ON  NOME_CORRETO_VIAGENS FROM 'professor'@'%';