USE ABD_03361_A_SARAH_NARAYAMY;

 CREATE TABLE COMIDAS_FAVORITAS (
 	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PESSOA VARCHAR(100) NOT NULL,
    COMIDA VARCHAR(100) NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    NOTA INT,
    CIDADE VARCHAR(50)
 );
 
 INSERT INTO COMIDAS_FAVORITAS (NOME_PESSOA, COMIDA, TIPO, NOTA, CIDADE) VALUES
	('SARAH', 'PIZZA', 'SALGADA', 10, 'SÃO PAULO'),
	('SARAH', 'EMPADA', 'SALGADA', 5, 'BELO HORIZONTE'),
	('SARAH', 'SORVETE', 'DOCE', 2, 'RIO DE JANEIRO'),
	('SARAH', 'PAD THAI', 'SALGADA', 10, 'BAHIA'),
	('SARAH', 'PETTI GAUTEAU', 'DOCE', 8, 'PORTO ALEGRE'),
	('SARAH', '43', 'BEBIDA', 9, 'BOIPEBA');
 
 -- SELECIONE TODAS AS COMIDAS COM NOTA MAIOR QUE 8
  
 SELECT * FROM COMIDAS_FAVORITAS WHERE NOTA > 8;
 
 -- MOSTRE APENAS O NOME DAS PESSOAS E SUAS COMIDAS FAVORITAS DO TIPO DOCE ORDENADAS PELO NOME
 
SELECT NOME_PESSOA, COMIDA FROM COMIDAS_FAVORITAS WHERE TIPO = 'DOCE' ORDER BY NOME_PESSOA ASC;

-- MOSTRE AS COMIDAS FAVORITAS DE QUEM MORA EM SÃO PAULO OU RIO DE JANEIRO

SELECT COMIDA, NOME_PESSOA FROM COMIDAS_FAVORITAS WHERE CIDADE IN ('SÃO PAULO', 'RIO DE JANEIRO');

-- ATUALIZE A NOTA DE UMA COMIDA ESPECÍFICA PARA 10 DICA: UPDATE NOME_DA_TABELA SET COLUNA = ... WHERE COLUNA =

SET SQL_SAFE_UPDATES = 0;
UPDATE COMIDAS_FAVORITAS SET NOTA = 10 WHERE TIPO ='BEBIDA';
SELECT COMIDA, NOTA FROM COMIDAS_FAVORITAS WHERE TIPO = 'BEBIDA';

-- O SAFE UPDATE É PORQUE ELE NÃO GARANTE O QUE SERÁ ATUALIZADO. USANDO O ID NÃO DA O PROBLEMA POR SER UMA CHAVE UNICA.

-- ATUALIZE O TIPO DE TODAS AS COMIDAS QUE CONTENHAM A PALAVRA PIZZA PARA SALGADO DICA: USE LIKE

UPDATE COMIDAS_FAVORITAS SET TIPO = 'SALGADO' WHERE COMIDA LIKE '%PIZZA%';
SELECT COMIDA, TIPO FROM COMIDAS_FAVORITAS WHERE COMIDA = 'PIZZA';

-- EXCLUA TODAS AS COMIDAS QUE TENHAM NOTA MENOR QUE 5

DELETE FROM COMIDAS_FAVORITAS WHERE NOTA < 5;
SELECT * FROM COMIDAS_FAVORITAS;

-- MOSTRE O NOME DA PESSOA E A COMIDA FAVORITA ONDE O NOME_TENHA MAIS DE 10 CARACTERES
-- E A NOTA ESTEJA ENTRE 7 E 10 DICA: USE LENGTH() E BETWEEN

SELECT NOME_PESSOA, COMIDA FROM COMIDAS_FAVORITAS WHERE LENGTH(NOME_PESSOA) > 10 AND NOTA BETWEEN 7 AND 10;




UPDATE COMIDAS_FAVORITAS SET NOME_PESSOA = 'ANA' WHERE COMIDA LIKE 'PIZZA';
UPDATE COMIDAS_FAVORITAS SET NOME_PESSOA = 'CARLOS' WHERE COMIDA LIKE 'EMPADA';
UPDATE COMIDAS_FAVORITAS SET NOME_PESSOA = 'BEATRIZ' WHERE COMIDA LIKE '43';
UPDATE COMIDAS_FAVORITAS SET NOME_PESSOA = 'FERNANDINHO' WHERE COMIDA LIKE 'PAD THAI';
UPDATE COMIDAS_FAVORITAS SET NOME_PESSOA = 'ALEXSANDRESSA' WHERE COMIDA LIKE 'PETTI GAUTEAU';
SET SQL_SAFE_UPDATES = 1;


 
 
 
 
 
 